/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminTeachersRouteImport } from './routes/admin/teachers'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminReportsRouteImport } from './routes/admin/reports'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminHelpersRouteImport } from './routes/admin/helpers'
import { Route as AdminFinanceRouteImport } from './routes/admin/finance'
import { Route as AdminCategoriesRouteImport } from './routes/admin/categories'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedDevRouteImport } from './routes/_authenticated/dev'
import { Route as AuthenticatedSkillsRouteRouteImport } from './routes/_authenticated/skills/route'
import { Route as AuthenticatedHelpRouteRouteImport } from './routes/_authenticated/help/route'
import { Route as AuthenticatedSkillsIndexRouteImport } from './routes/_authenticated/skills/index'
import { Route as AuthenticatedHelpIndexRouteImport } from './routes/_authenticated/help/index'
import { Route as ApiPublicRazorpayWebhookRouteImport } from './routes/api/public/razorpay-webhook'
import { Route as AuthenticatedSkillsTeachRouteImport } from './routes/_authenticated/skills/teach'
import { Route as AuthenticatedSkillsProfileRouteImport } from './routes/_authenticated/skills/profile'
import { Route as AuthenticatedSkillsLearnRouteImport } from './routes/_authenticated/skills/learn'
import { Route as AuthenticatedSkillsBookingsRouteImport } from './routes/_authenticated/skills/bookings'
import { Route as AuthenticatedHelpProfileRouteImport } from './routes/_authenticated/help/profile'
import { Route as AuthenticatedHelpNearbyRouteImport } from './routes/_authenticated/help/nearby'
import { Route as AuthenticatedHelpDashboardRouteImport } from './routes/_authenticated/help/dashboard'
import { Route as AuthenticatedHelpAskRouteImport } from './routes/_authenticated/help/ask'
import { Route as AuthenticatedAdminTrustRouteImport } from './routes/_authenticated/admin/trust'
import { Route as AuthenticatedSkillsTeacherTeacherIdRouteImport } from './routes/_authenticated/skills/teacher.$teacherId'
import { Route as AuthenticatedHelpRequestsIdRouteImport } from './routes/_authenticated/help/requests.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminTeachersRoute = AdminTeachersRouteImport.update({
  id: '/teachers',
  path: '/teachers',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminHelpersRoute = AdminHelpersRouteImport.update({
  id: '/helpers',
  path: '/helpers',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminFinanceRoute = AdminFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDevRoute = AuthenticatedDevRouteImport.update({
  id: '/dev',
  path: '/dev',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSkillsRouteRoute =
  AuthenticatedSkillsRouteRouteImport.update({
    id: '/skills',
    path: '/skills',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHelpRouteRoute = AuthenticatedHelpRouteRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSkillsIndexRoute =
  AuthenticatedSkillsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSkillsRouteRoute,
  } as any)
const AuthenticatedHelpIndexRoute = AuthenticatedHelpIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedHelpRouteRoute,
} as any)
const ApiPublicRazorpayWebhookRoute =
  ApiPublicRazorpayWebhookRouteImport.update({
    id: '/api/public/razorpay-webhook',
    path: '/api/public/razorpay-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedSkillsTeachRoute =
  AuthenticatedSkillsTeachRouteImport.update({
    id: '/teach',
    path: '/teach',
    getParentRoute: () => AuthenticatedSkillsRouteRoute,
  } as any)
const AuthenticatedSkillsProfileRoute =
  AuthenticatedSkillsProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedSkillsRouteRoute,
  } as any)
const AuthenticatedSkillsLearnRoute =
  AuthenticatedSkillsLearnRouteImport.update({
    id: '/learn',
    path: '/learn',
    getParentRoute: () => AuthenticatedSkillsRouteRoute,
  } as any)
const AuthenticatedSkillsBookingsRoute =
  AuthenticatedSkillsBookingsRouteImport.update({
    id: '/bookings',
    path: '/bookings',
    getParentRoute: () => AuthenticatedSkillsRouteRoute,
  } as any)
const AuthenticatedHelpProfileRoute =
  AuthenticatedHelpProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedHelpRouteRoute,
  } as any)
const AuthenticatedHelpNearbyRoute = AuthenticatedHelpNearbyRouteImport.update({
  id: '/nearby',
  path: '/nearby',
  getParentRoute: () => AuthenticatedHelpRouteRoute,
} as any)
const AuthenticatedHelpDashboardRoute =
  AuthenticatedHelpDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedHelpRouteRoute,
  } as any)
const AuthenticatedHelpAskRoute = AuthenticatedHelpAskRouteImport.update({
  id: '/ask',
  path: '/ask',
  getParentRoute: () => AuthenticatedHelpRouteRoute,
} as any)
const AuthenticatedAdminTrustRoute = AuthenticatedAdminTrustRouteImport.update({
  id: '/admin/trust',
  path: '/admin/trust',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSkillsTeacherTeacherIdRoute =
  AuthenticatedSkillsTeacherTeacherIdRouteImport.update({
    id: '/teacher/$teacherId',
    path: '/teacher/$teacherId',
    getParentRoute: () => AuthenticatedSkillsRouteRoute,
  } as any)
const AuthenticatedHelpRequestsIdRoute =
  AuthenticatedHelpRequestsIdRouteImport.update({
    id: '/requests/$id',
    path: '/requests/$id',
    getParentRoute: () => AuthenticatedHelpRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/help': typeof AuthenticatedHelpRouteRouteWithChildren
  '/skills': typeof AuthenticatedSkillsRouteRouteWithChildren
  '/dev': typeof AuthenticatedDevRoute
  '/home': typeof AuthenticatedHomeRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/helpers': typeof AdminHelpersRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/teachers': typeof AdminTeachersRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/trust': typeof AuthenticatedAdminTrustRoute
  '/help/ask': typeof AuthenticatedHelpAskRoute
  '/help/dashboard': typeof AuthenticatedHelpDashboardRoute
  '/help/nearby': typeof AuthenticatedHelpNearbyRoute
  '/help/profile': typeof AuthenticatedHelpProfileRoute
  '/skills/bookings': typeof AuthenticatedSkillsBookingsRoute
  '/skills/learn': typeof AuthenticatedSkillsLearnRoute
  '/skills/profile': typeof AuthenticatedSkillsProfileRoute
  '/skills/teach': typeof AuthenticatedSkillsTeachRoute
  '/api/public/razorpay-webhook': typeof ApiPublicRazorpayWebhookRoute
  '/help/': typeof AuthenticatedHelpIndexRoute
  '/skills/': typeof AuthenticatedSkillsIndexRoute
  '/help/requests/$id': typeof AuthenticatedHelpRequestsIdRoute
  '/skills/teacher/$teacherId': typeof AuthenticatedSkillsTeacherTeacherIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dev': typeof AuthenticatedDevRoute
  '/home': typeof AuthenticatedHomeRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/helpers': typeof AdminHelpersRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/teachers': typeof AdminTeachersRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin': typeof AdminIndexRoute
  '/admin/trust': typeof AuthenticatedAdminTrustRoute
  '/help/ask': typeof AuthenticatedHelpAskRoute
  '/help/dashboard': typeof AuthenticatedHelpDashboardRoute
  '/help/nearby': typeof AuthenticatedHelpNearbyRoute
  '/help/profile': typeof AuthenticatedHelpProfileRoute
  '/skills/bookings': typeof AuthenticatedSkillsBookingsRoute
  '/skills/learn': typeof AuthenticatedSkillsLearnRoute
  '/skills/profile': typeof AuthenticatedSkillsProfileRoute
  '/skills/teach': typeof AuthenticatedSkillsTeachRoute
  '/api/public/razorpay-webhook': typeof ApiPublicRazorpayWebhookRoute
  '/help': typeof AuthenticatedHelpIndexRoute
  '/skills': typeof AuthenticatedSkillsIndexRoute
  '/help/requests/$id': typeof AuthenticatedHelpRequestsIdRoute
  '/skills/teacher/$teacherId': typeof AuthenticatedSkillsTeacherTeacherIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/help': typeof AuthenticatedHelpRouteRouteWithChildren
  '/_authenticated/skills': typeof AuthenticatedSkillsRouteRouteWithChildren
  '/_authenticated/dev': typeof AuthenticatedDevRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/helpers': typeof AdminHelpersRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/teachers': typeof AdminTeachersRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/': typeof AdminIndexRoute
  '/_authenticated/admin/trust': typeof AuthenticatedAdminTrustRoute
  '/_authenticated/help/ask': typeof AuthenticatedHelpAskRoute
  '/_authenticated/help/dashboard': typeof AuthenticatedHelpDashboardRoute
  '/_authenticated/help/nearby': typeof AuthenticatedHelpNearbyRoute
  '/_authenticated/help/profile': typeof AuthenticatedHelpProfileRoute
  '/_authenticated/skills/bookings': typeof AuthenticatedSkillsBookingsRoute
  '/_authenticated/skills/learn': typeof AuthenticatedSkillsLearnRoute
  '/_authenticated/skills/profile': typeof AuthenticatedSkillsProfileRoute
  '/_authenticated/skills/teach': typeof AuthenticatedSkillsTeachRoute
  '/api/public/razorpay-webhook': typeof ApiPublicRazorpayWebhookRoute
  '/_authenticated/help/': typeof AuthenticatedHelpIndexRoute
  '/_authenticated/skills/': typeof AuthenticatedSkillsIndexRoute
  '/_authenticated/help/requests/$id': typeof AuthenticatedHelpRequestsIdRoute
  '/_authenticated/skills/teacher/$teacherId': typeof AuthenticatedSkillsTeacherTeacherIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/help'
    | '/skills'
    | '/dev'
    | '/home'
    | '/admin/categories'
    | '/admin/finance'
    | '/admin/helpers'
    | '/admin/login'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/teachers'
    | '/admin/users'
    | '/admin/'
    | '/admin/trust'
    | '/help/ask'
    | '/help/dashboard'
    | '/help/nearby'
    | '/help/profile'
    | '/skills/bookings'
    | '/skills/learn'
    | '/skills/profile'
    | '/skills/teach'
    | '/api/public/razorpay-webhook'
    | '/help/'
    | '/skills/'
    | '/help/requests/$id'
    | '/skills/teacher/$teacherId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dev'
    | '/home'
    | '/admin/categories'
    | '/admin/finance'
    | '/admin/helpers'
    | '/admin/login'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/teachers'
    | '/admin/users'
    | '/admin'
    | '/admin/trust'
    | '/help/ask'
    | '/help/dashboard'
    | '/help/nearby'
    | '/help/profile'
    | '/skills/bookings'
    | '/skills/learn'
    | '/skills/profile'
    | '/skills/teach'
    | '/api/public/razorpay-webhook'
    | '/help'
    | '/skills'
    | '/help/requests/$id'
    | '/skills/teacher/$teacherId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/admin'
    | '/auth'
    | '/_authenticated/help'
    | '/_authenticated/skills'
    | '/_authenticated/dev'
    | '/_authenticated/home'
    | '/admin/categories'
    | '/admin/finance'
    | '/admin/helpers'
    | '/admin/login'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/teachers'
    | '/admin/users'
    | '/admin/'
    | '/_authenticated/admin/trust'
    | '/_authenticated/help/ask'
    | '/_authenticated/help/dashboard'
    | '/_authenticated/help/nearby'
    | '/_authenticated/help/profile'
    | '/_authenticated/skills/bookings'
    | '/_authenticated/skills/learn'
    | '/_authenticated/skills/profile'
    | '/_authenticated/skills/teach'
    | '/api/public/razorpay-webhook'
    | '/_authenticated/help/'
    | '/_authenticated/skills/'
    | '/_authenticated/help/requests/$id'
    | '/_authenticated/skills/teacher/$teacherId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicRazorpayWebhookRoute: typeof ApiPublicRazorpayWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/teachers': {
      id: '/admin/teachers'
      path: '/teachers'
      fullPath: '/admin/teachers'
      preLoaderRoute: typeof AdminTeachersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/helpers': {
      id: '/admin/helpers'
      path: '/helpers'
      fullPath: '/admin/helpers'
      preLoaderRoute: typeof AdminHelpersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/finance': {
      id: '/admin/finance'
      path: '/finance'
      fullPath: '/admin/finance'
      preLoaderRoute: typeof AdminFinanceRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dev': {
      id: '/_authenticated/dev'
      path: '/dev'
      fullPath: '/dev'
      preLoaderRoute: typeof AuthenticatedDevRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/skills': {
      id: '/_authenticated/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof AuthenticatedSkillsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/help': {
      id: '/_authenticated/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof AuthenticatedHelpRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/skills/': {
      id: '/_authenticated/skills/'
      path: '/'
      fullPath: '/skills/'
      preLoaderRoute: typeof AuthenticatedSkillsIndexRouteImport
      parentRoute: typeof AuthenticatedSkillsRouteRoute
    }
    '/_authenticated/help/': {
      id: '/_authenticated/help/'
      path: '/'
      fullPath: '/help/'
      preLoaderRoute: typeof AuthenticatedHelpIndexRouteImport
      parentRoute: typeof AuthenticatedHelpRouteRoute
    }
    '/api/public/razorpay-webhook': {
      id: '/api/public/razorpay-webhook'
      path: '/api/public/razorpay-webhook'
      fullPath: '/api/public/razorpay-webhook'
      preLoaderRoute: typeof ApiPublicRazorpayWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/skills/teach': {
      id: '/_authenticated/skills/teach'
      path: '/teach'
      fullPath: '/skills/teach'
      preLoaderRoute: typeof AuthenticatedSkillsTeachRouteImport
      parentRoute: typeof AuthenticatedSkillsRouteRoute
    }
    '/_authenticated/skills/profile': {
      id: '/_authenticated/skills/profile'
      path: '/profile'
      fullPath: '/skills/profile'
      preLoaderRoute: typeof AuthenticatedSkillsProfileRouteImport
      parentRoute: typeof AuthenticatedSkillsRouteRoute
    }
    '/_authenticated/skills/learn': {
      id: '/_authenticated/skills/learn'
      path: '/learn'
      fullPath: '/skills/learn'
      preLoaderRoute: typeof AuthenticatedSkillsLearnRouteImport
      parentRoute: typeof AuthenticatedSkillsRouteRoute
    }
    '/_authenticated/skills/bookings': {
      id: '/_authenticated/skills/bookings'
      path: '/bookings'
      fullPath: '/skills/bookings'
      preLoaderRoute: typeof AuthenticatedSkillsBookingsRouteImport
      parentRoute: typeof AuthenticatedSkillsRouteRoute
    }
    '/_authenticated/help/profile': {
      id: '/_authenticated/help/profile'
      path: '/profile'
      fullPath: '/help/profile'
      preLoaderRoute: typeof AuthenticatedHelpProfileRouteImport
      parentRoute: typeof AuthenticatedHelpRouteRoute
    }
    '/_authenticated/help/nearby': {
      id: '/_authenticated/help/nearby'
      path: '/nearby'
      fullPath: '/help/nearby'
      preLoaderRoute: typeof AuthenticatedHelpNearbyRouteImport
      parentRoute: typeof AuthenticatedHelpRouteRoute
    }
    '/_authenticated/help/dashboard': {
      id: '/_authenticated/help/dashboard'
      path: '/dashboard'
      fullPath: '/help/dashboard'
      preLoaderRoute: typeof AuthenticatedHelpDashboardRouteImport
      parentRoute: typeof AuthenticatedHelpRouteRoute
    }
    '/_authenticated/help/ask': {
      id: '/_authenticated/help/ask'
      path: '/ask'
      fullPath: '/help/ask'
      preLoaderRoute: typeof AuthenticatedHelpAskRouteImport
      parentRoute: typeof AuthenticatedHelpRouteRoute
    }
    '/_authenticated/admin/trust': {
      id: '/_authenticated/admin/trust'
      path: '/admin/trust'
      fullPath: '/admin/trust'
      preLoaderRoute: typeof AuthenticatedAdminTrustRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/skills/teacher/$teacherId': {
      id: '/_authenticated/skills/teacher/$teacherId'
      path: '/teacher/$teacherId'
      fullPath: '/skills/teacher/$teacherId'
      preLoaderRoute: typeof AuthenticatedSkillsTeacherTeacherIdRouteImport
      parentRoute: typeof AuthenticatedSkillsRouteRoute
    }
    '/_authenticated/help/requests/$id': {
      id: '/_authenticated/help/requests/$id'
      path: '/requests/$id'
      fullPath: '/help/requests/$id'
      preLoaderRoute: typeof AuthenticatedHelpRequestsIdRouteImport
      parentRoute: typeof AuthenticatedHelpRouteRoute
    }
  }
}

interface AuthenticatedHelpRouteRouteChildren {
  AuthenticatedHelpAskRoute: typeof AuthenticatedHelpAskRoute
  AuthenticatedHelpDashboardRoute: typeof AuthenticatedHelpDashboardRoute
  AuthenticatedHelpNearbyRoute: typeof AuthenticatedHelpNearbyRoute
  AuthenticatedHelpProfileRoute: typeof AuthenticatedHelpProfileRoute
  AuthenticatedHelpIndexRoute: typeof AuthenticatedHelpIndexRoute
  AuthenticatedHelpRequestsIdRoute: typeof AuthenticatedHelpRequestsIdRoute
}

const AuthenticatedHelpRouteRouteChildren: AuthenticatedHelpRouteRouteChildren =
  {
    AuthenticatedHelpAskRoute: AuthenticatedHelpAskRoute,
    AuthenticatedHelpDashboardRoute: AuthenticatedHelpDashboardRoute,
    AuthenticatedHelpNearbyRoute: AuthenticatedHelpNearbyRoute,
    AuthenticatedHelpProfileRoute: AuthenticatedHelpProfileRoute,
    AuthenticatedHelpIndexRoute: AuthenticatedHelpIndexRoute,
    AuthenticatedHelpRequestsIdRoute: AuthenticatedHelpRequestsIdRoute,
  }

const AuthenticatedHelpRouteRouteWithChildren =
  AuthenticatedHelpRouteRoute._addFileChildren(
    AuthenticatedHelpRouteRouteChildren,
  )

interface AuthenticatedSkillsRouteRouteChildren {
  AuthenticatedSkillsBookingsRoute: typeof AuthenticatedSkillsBookingsRoute
  AuthenticatedSkillsLearnRoute: typeof AuthenticatedSkillsLearnRoute
  AuthenticatedSkillsProfileRoute: typeof AuthenticatedSkillsProfileRoute
  AuthenticatedSkillsTeachRoute: typeof AuthenticatedSkillsTeachRoute
  AuthenticatedSkillsIndexRoute: typeof AuthenticatedSkillsIndexRoute
  AuthenticatedSkillsTeacherTeacherIdRoute: typeof AuthenticatedSkillsTeacherTeacherIdRoute
}

const AuthenticatedSkillsRouteRouteChildren: AuthenticatedSkillsRouteRouteChildren =
  {
    AuthenticatedSkillsBookingsRoute: AuthenticatedSkillsBookingsRoute,
    AuthenticatedSkillsLearnRoute: AuthenticatedSkillsLearnRoute,
    AuthenticatedSkillsProfileRoute: AuthenticatedSkillsProfileRoute,
    AuthenticatedSkillsTeachRoute: AuthenticatedSkillsTeachRoute,
    AuthenticatedSkillsIndexRoute: AuthenticatedSkillsIndexRoute,
    AuthenticatedSkillsTeacherTeacherIdRoute:
      AuthenticatedSkillsTeacherTeacherIdRoute,
  }

const AuthenticatedSkillsRouteRouteWithChildren =
  AuthenticatedSkillsRouteRoute._addFileChildren(
    AuthenticatedSkillsRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedHelpRouteRoute: typeof AuthenticatedHelpRouteRouteWithChildren
  AuthenticatedSkillsRouteRoute: typeof AuthenticatedSkillsRouteRouteWithChildren
  AuthenticatedDevRoute: typeof AuthenticatedDevRoute
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedAdminTrustRoute: typeof AuthenticatedAdminTrustRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedHelpRouteRoute: AuthenticatedHelpRouteRouteWithChildren,
  AuthenticatedSkillsRouteRoute: AuthenticatedSkillsRouteRouteWithChildren,
  AuthenticatedDevRoute: AuthenticatedDevRoute,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedAdminTrustRoute: AuthenticatedAdminTrustRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AdminRouteRouteChildren {
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminFinanceRoute: typeof AdminFinanceRoute
  AdminHelpersRoute: typeof AdminHelpersRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminTeachersRoute: typeof AdminTeachersRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminFinanceRoute: AdminFinanceRoute,
  AdminHelpersRoute: AdminHelpersRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminTeachersRoute: AdminTeachersRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicRazorpayWebhookRoute: ApiPublicRazorpayWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
